go_import_path: github.com/gregf/podfetcher

language: go
go:
  - 1.9.x
  - 1.10.x
  - tip

os:
  - linux
  - freebsd
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

sudo: false
